import { Check, Globe2 } from "lucide-react";
import { useCurrency } from "@/hooks/useCurrency";
import { COUNTRIES, countryName } from "@/lib/countries";
import { DropdownMenu, DropdownMenuContent, DropdownMenuLabel, DropdownMenuRadioGroup, DropdownMenuRadioItem, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";

export default function RegionalPreferences() {
  const { country, currency, currencies, setCountry, setCurrencyCode } = useCurrency();
  return <DropdownMenu><DropdownMenuTrigger asChild><button aria-label="Delivery country and currency" className="flex items-center gap-1.5 rounded-full px-2 py-2 text-[#111111] transition-colors hover:bg-[#F2F3F5] dark:text-[#FAF5F2] dark:hover:bg-[#222222]"><Globe2 className="h-4 w-4" /><span className="hidden xl:inline text-xs font-semibold">{country ? countryName(country) : "Ship to"}</span><span className="hidden xl:inline text-[10px] text-[#888880]">{currency.code}</span></button></DropdownMenuTrigger><DropdownMenuContent align="end" className="w-72 p-0"><div className="border-b border-border px-3 py-3"><DropdownMenuLabel className="p-0 text-sm font-semibold">Delivery & currency</DropdownMenuLabel><p className="mt-1 text-xs font-normal text-muted-foreground">Your destination filters availability; prices use your selected display currency.</p></div><div className="max-h-56 overflow-y-auto p-1"><DropdownMenuRadioGroup value={country || "anywhere"} onValueChange={(value) => setCountry(value === "anywhere" ? null : value)}><DropdownMenuRadioItem value="anywhere" className="text-xs">Ship anywhere</DropdownMenuRadioItem>{COUNTRIES.map((item) => <DropdownMenuRadioItem key={item.code} value={item.code} className="text-xs">{item.name}</DropdownMenuRadioItem>)}</DropdownMenuRadioGroup></div><DropdownMenuSeparator /><div className="p-2"><p className="px-2 pb-1 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Display currency</p><div className="grid grid-cols-2 gap-1">{Object.entries(currencies).map(([code, info]) => <button key={code} type="button" onClick={() => setCurrencyCode(code)} className={`flex items-center gap-1.5 rounded-md px-2 py-1.5 text-left text-xs transition-colors ${currency.code === code ? "bg-primary/10 text-primary" : "hover:bg-muted"}`}><span>{info.symbol}</span><span>{code}</span>{currency.code === code && <Check className="ml-auto h-3 w-3" />}</button>)}</div></div></DropdownMenuContent></DropdownMenu>;
}
